& "$PsScriptRoot\bdr\storage-config.ps1"
& "$PsScriptRoot\bdr\filesystem-config.ps1"
& "$PsScriptRoot\bdr\net-config.ps1"
# & "$PsScriptRoot\servers\userprofile-config.ps1"
& "$PsScriptRoot\servers\windows-config.ps1"
& "$PsScriptRoot\servers\deploy-features.ps1"
& "$PsScriptRoot\servers\deploy-oem-tools.ps1"
& "$PsScriptRoot\servers\deploy-apps.ps1"
# & "$PsScriptRoot\debloat-windows-10\scripts\remove-default-apps.ps1"
# & "$PsScriptRoot\debloat-windows-10\scripts\remove-onedrive.ps1"
& "$PsScriptRoot\rmm\deploy-automate.ps1"
& "$PsScriptRoot\bitlocker.ps1"
& "$PsScriptRoot\servers\update-windows.ps1"